Application.ensure_all_started(:mox)
Mox.defmock(Gust.DAGLoaderMock, for: Gust.DAG.Loader)
Mox.defmock(Gust.FileMonitorMock, for: Gust.FileMonitor)
Mox.defmock(Gust.DAGParserMock, for: Gust.DAG.Parser)
Mox.defmock(Gust.DAGParserAdapterMock, for: Gust.DAG.Parser.Adapter)
Mox.defmock(Gust.DAGRunnerSupervisorMock, for: Gust.DAG.RunnerSupervisor)
Mox.defmock(Gust.DAGTerminatorMock, for: Gust.DAG.Terminator)
Mox.defmock(Gust.RunGatewayMock, for: Gust.DAG.Runner.RunGateway)
Mox.defmock(Gust.DAGTaskRunnerSupervisorMock, for: Gust.DAG.TaskRunnerSupervisor)
Mox.defmock(Gust.DAGStageCoordinatorMock, for: Gust.DAG.StageCoordinator)
Mox.defmock(Gust.DAGLoggerMock, for: Gust.DAG.Logger)
Mox.defmock(Gust.DAGRunTriggerMock, for: Gust.DAG.Run.Trigger)
Mox.defmock(Gust.DAGTaskWaiterMock, for: Gust.DAG.TaskWaiter)
Mox.defmock(Gust.DAGTaskDelayerMock, for: Gust.DAG.TaskDelayer)
Mox.defmock(Gust.DAGTaskExpanderMock, for: Gust.DAG.TaskExpander)
Mox.defmock(Gust.DAGErrorReporterMock, for: Gust.DAG.Run.ErrorReporter)
Mox.defmock(Gust.DBLockerMock, for: Gust.DBLocker)
Mox.defmock(Gust.RunClaimMock, for: Gust.Run.Claim)
Mox.defmock(Gust.RuntimeAdapterMock, for: Gust.DAG.Runtime.Adapter)
Mox.defmock(Gust.PGNotifierMock, for: Gust.PGNotifier)

Application.put_env(:gust, :dag_parser, Gust.DAGParserMock)
Application.put_env(:gust, :dag_loader, Gust.DAGLoaderMock)
Application.put_env(:gust, :file_monitor, Gust.FileMonitorMock)
Application.put_env(:gust, :dag_runner_supervisor, Gust.DAGRunnerSupervisorMock)
Application.put_env(:gust, :dag_task_runner_supervisor, Gust.DAGTaskRunnerSupervisorMock)
Application.put_env(:gust, :dag_stage_coordinator, Gust.DAGStageCoordinatorMock)
Application.put_env(:gust, :dag_logger, Gust.DAGLoggerMock)
Application.put_env(:gust, :dag_run_trigger, Gust.DAGRunTriggerMock)
Application.put_env(:gust, :dag_task_delayer, Gust.DAGTaskDelayerMock)
Application.put_env(:gust, :db_locker, Gust.DBLockerMock)
Application.put_env(:gust, :run_claim, Gust.RunClaimMock)
Application.put_env(:gust, :dag_task_expander, Gust.DAGTaskExpanderMock)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Gust.Repo, :manual)
